// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"time"
)

type Customer struct {
	ID        int32
	Firstname string
	Lastname  string
	Email     string
}

type Order struct {
	ID          int32
	Customerid  int32
	Orderdate   time.Time
	Totalamount float64
}

type Orderitem struct {
	ID        int32
	Orderid   int32
	Productid int32
	Quantity  int32
	Subtotal  float64
}

type Product struct {
	ID    int32
	Name  string
	Price float64
}
